language: java

jdk: openjdk11

sudo: false   # Linux OS: run in container

matrix:
  include:
    # Headed Linux
    - os: linux
      dist: trusty
      jdk: openjdk11
    # Headless Linux
    - os: linux
      dist: trusty
      jdk: openjdk11
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x gradlew
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install: true

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == osx ]]; then brew update; brew cask reinstall caskroom/versions/java8; fi

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/